# Generated by Django 5.2.8 on 2025-12-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image_url_alter_book_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
    ]
